-- MySQL Script generated by MySQL Workbench
-- Sun Jun  9 17:14:31 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE =
        'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Library
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Library`;

-- -----------------------------------------------------
-- Schema Library
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Library`;
USE `Library`;

-- -----------------------------------------------------
-- Table `Library`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Library`.`Users`;

CREATE TABLE IF NOT EXISTS `Library`.`Users`
(
    `EmailAddress` VARCHAR(256) NOT NULL,
    `PasswordHash` CHAR(60)     NOT NULL,
    `Role`         BIT(2)       NOT NULL DEFAULT 0,
    `FirstName`    VARCHAR(256) NULL,
    `LastName`     VARCHAR(256) NULL,
    PRIMARY KEY (`EmailAddress`),
    UNIQUE INDEX `emailAddress_UNIQUE` (`EmailAddress` ASC) VISIBLE
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Library`.`Books`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Library`.`Books`;

CREATE TABLE IF NOT EXISTS `Library`.`Books`
(
    `ISBN`            CHAR(17)     NOT NULL,
    `Title`           TEXT         NOT NULL,
    `Author`          VARCHAR(512) NOT NULL,
    `PublicationDate` DATE         NOT NULL,
    `Publisher`       VARCHAR(512) NOT NULL,
    PRIMARY KEY (`ISBN`),
    UNIQUE INDEX `ISBN_UNIQUE` (`ISBN` ASC) VISIBLE
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Library`.`Categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Library`.`Categories`;

CREATE TABLE IF NOT EXISTS `Library`.`Categories`
(
    `Name`        VARCHAR(256) NOT NULL,
    `Description` TEXT         NULL,
    PRIMARY KEY (`Name`),
    UNIQUE INDEX `Name_UNIQUE` (`Name` ASC) VISIBLE
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Library`.`BookCategories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Library`.`BookCategories`;

CREATE TABLE IF NOT EXISTS `Library`.`BookCategories`
(
    `BookISBN`     VARCHAR(17)  NOT NULL,
    `CategoryName` VARCHAR(256) NOT NULL,
    PRIMARY KEY (`BookISBN`, `CategoryName`),
    INDEX `fk_BookCategories_Category_idx` (`CategoryName` ASC) VISIBLE,
    CONSTRAINT `fk_BookCategories_Book`
        FOREIGN KEY (`BookISBN`)
            REFERENCES `Library`.`Books` (`ISBN`)
            ON DELETE CASCADE
            ON UPDATE CASCADE,
    CONSTRAINT `fk_BookCategories_Category`
        FOREIGN KEY (`CategoryName`)
            REFERENCES `Library`.`Categories` (`Name`)
            ON DELETE CASCADE
            ON UPDATE CASCADE
)
    ENGINE = InnoDB;

SET SQL_MODE = '';
DROP USER IF EXISTS LibraryDBUser;
SET SQL_MODE =
        'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
CREATE USER 'LibraryDBUser' IDENTIFIED BY 'LibraryDBPassword';

GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `Library`.* TO 'LibraryDBUser';

SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `Library`.`Users`
-- -----------------------------------------------------
START TRANSACTION;
USE `Library`;
INSERT INTO `Library`.`Users` (`EmailAddress`, `PasswordHash`, `Role`, `FirstName`, `LastName`)
VALUES ('federico.paoloni@dotnetlibrary.com', '$2a$14$ETd8.LL8FI77cgFnG2LDcOitB88aWW5NNT91taNkmCUoxdBo8uyH6', 1,
        'Federico', 'Paoloni');
INSERT INTO `Library`.`Users` (`EmailAddress`, `PasswordHash`, `Role`, `FirstName`, `LastName`)
VALUES ('massimo.pavoni@dotnetlibrary.com', '$2a$14$PYkLH3s4m2sRG4Pzj.ZzyeaKfyEPT4EonORHfd9YsjELLz9TpHUom', 2,
        'Massimo', 'Pavoni');
INSERT INTO `Library`.`Users` (`EmailAddress`, `PasswordHash`, `Role`, `FirstName`, `LastName`)
VALUES ('rosario.culmone@dotnetlibrary.com', '$2a$14$JwB2CqrwXHNQQyX/lCx7TOLKvSwiFWJY7Ega2zoQLc.CAiXuJ9W7G', 1,
        'Rosario', 'Culmone');
INSERT INTO `Library`.`Users` (`EmailAddress`, `PasswordHash`, `Role`, `FirstName`, `LastName`)
VALUES ('luca.padovani@dotnetlibrary.com', '$2a$14$SFDJfMsqkhIg6AYLQGHSz.X8B2o7Qrfh1yxm3bbdggDOIBG60SE.O', 2, 'Luca',
        'Padovani');
INSERT INTO `Library`.`Users` (`EmailAddress`, `PasswordHash`, `Role`, `FirstName`, `LastName`)
VALUES ('marco.caputo@dotnetlibrary.com', '$2a$14$dxiem5c7hD/Kg8jEbtgXneDu5gvAvHvMFhntbJW6cCdfviQO9OFCe', 0, 'Marco',
        'Caputo');
INSERT INTO `Library`.`Users` (`EmailAddress`, `PasswordHash`, `Role`, `FirstName`, `LastName`)
VALUES ('lorenzo.lupi@dotnetlibrary.com', '$2a$14$T8HhufhFat4xZeLh7NoVluYLOZS10db2rE4dxmFcJ1wR6g9NOcrDS', 0, 'Lorenzo',
        'Lupi');

COMMIT;


-- -----------------------------------------------------
-- Data for table `Library`.`Categories`
-- -----------------------------------------------------
START TRANSACTION;
USE `Library`;
INSERT INTO `Library`.`Categories` (`Name`, `Description`)
VALUES ('Fiction', 'Imaginative and narrative prose, including novels and short stories.');
INSERT INTO `Library`.`Categories` (`Name`, `Description`)
VALUES ('NonFiction', 'Factual books covering a wide range of subjects.');
INSERT INTO `Library`.`Categories` (`Name`, `Description`)
VALUES ('Mystery', 'Fictional works dealing with the solution of a crime or unraveling secrets.');
INSERT INTO `Library`.`Categories` (`Name`, `Description`)
VALUES ('Fantasy', 'Fiction set in an imaginative universe, often with magical elements.');
INSERT INTO `Library`.`Categories` (`Name`, `Description`)
VALUES ('ScienceFiction', 'Fiction based on futuristic concepts, advanced science, and technology.');
INSERT INTO `Library`.`Categories` (`Name`, `Description`)
VALUES ('Romance', 'Stories focused on romantic relationships.');
INSERT INTO `Library`.`Categories` (`Name`, `Description`)
VALUES ('Horror', 'Fiction designed to scare and thrill, often involving supernatural elements.');
INSERT INTO `Library`.`Categories` (`Name`, `Description`)
VALUES ('Thriller', 'Fast-paced, suspenseful stories with high stakes and excitement.');
INSERT INTO `Library`.`Categories` (`Name`, `Description`)
VALUES ('Biography', 'Nonfiction works detailing the life of a person.');
INSERT INTO `Library`.`Categories` (`Name`, `Description`)
VALUES ('SelfHelp', 'Books offering advice and strategies for personal improvement.');
INSERT INTO `Library`.`Categories` (`Name`, `Description`)
VALUES ('History', 'Books exploring historical events, periods, and figures.');
INSERT INTO `Library`.`Categories` (`Name`, `Description`)
VALUES ('Philosophy', 'Works that explore fundamental questions about existence, knowledge, and ethics.');
INSERT INTO `Library`.`Categories` (`Name`, `Description`)
VALUES ('Science', 'Books focused on scientific topics and discoveries.');
INSERT INTO `Library`.`Categories` (`Name`, `Description`)
VALUES ('Travel', 'Literature detailing journeys, travel guides, and explorations.');
INSERT INTO `Library`.`Categories` (`Name`, `Description`)
VALUES ('Cooking', 'Collections of recipes and culinary techniques.');
INSERT INTO `Library`.`Categories` (`Name`, `Description`)
VALUES ('Children', 'Books aimed at young readers, often with illustrations and simple language.');
INSERT INTO `Library`.`Categories` (`Name`, `Description`)
VALUES ('YoungAdult', 'Fiction aimed at teenage readers, dealing with their issues and experiences.');
INSERT INTO `Library`.`Categories` (`Name`, `Description`)
VALUES ('Poetry', 'Collections of poems, expressing emotions and ideas through verse.');
INSERT INTO `Library`.`Categories` (`Name`, `Description`)
VALUES ('Comics', 'Illustrated stories presented in sequential panels, often combining text and visuals.');
INSERT INTO `Library`.`Categories` (`Name`, `Description`)
VALUES ('Art', 'Books about visual arts, including techniques, history, and artists.');
INSERT INTO `Library`.`Categories` (`Name`, `Description`)
VALUES ('Religion', 'Works exploring religious beliefs, practices, and philosophies.');
INSERT INTO `Library`.`Categories` (`Name`, `Description`)
VALUES ('Drama', 'Plays and scripts for theatrical performance.');
INSERT INTO `Library`.`Categories` (`Name`, `Description`)
VALUES ('Education', 'Books focused on teaching methods, pedagogy, and educational theory.');
INSERT INTO `Library`.`Categories` (`Name`, `Description`)
VALUES ('Health', 'Books on medical topics, wellness, and fitness.');
INSERT INTO `Library`.`Categories` (`Name`, `Description`)
VALUES ('Economics', 'Literature exploring economic theories, principles, and practices.');
INSERT INTO `Library`.`Categories` (`Name`, `Description`)
VALUES ('Law', 'Books covering legal principles, case studies, and legal theory.');
INSERT INTO `Library`.`Categories` (`Name`, `Description`)
VALUES ('Politics', 'Works exploring political systems, theories, and current events.');
INSERT INTO `Library`.`Categories` (`Name`, `Description`)
VALUES ('Technology', 'Books on technological advancements and their applications.');
INSERT INTO `Library`.`Categories` (`Name`, `Description`)
VALUES ('Sports', 'Books on various sports, including biographies, techniques, and history.');
INSERT INTO `Library`.`Categories` (`Name`, `Description`)
VALUES ('Music', 'Literature on music theory, history, and biographies of musicians.');

COMMIT;

