# This is a generated file. Not intended for manual editing.
services:
  api:
    build:
      context: "/home/damax/Documents/Repositories/DotNetLibrary/DotNetLibrary"
      dockerfile: "DotNetLibrary.API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/DotNetLibrary.API.dll"
    environment:
      DOTNET_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "dotnetlibrary-api:dev"
    ports: []
    volumes:
    - "/home/damax/.nuget/packages:/home/app/.nuget/packages"
    - "/home/damax/Documents/Repositories/DotNetLibrary/DotNetLibrary/DotNetLibrary.API:/app:rw"
    - "/home/damax/Documents/Repositories/DotNetLibrary/DotNetLibrary:/src:rw"
    working_dir: "/app"
